-- 16-digit Registration ID generated by the PMJAY/MJPJAY Yojana portal
-- when a patient case is registered there. Captured per visit because each
-- visit/case gets its own registration ID. Distinct from ayushman_id.
ALTER TABLE public.visits ADD COLUMN IF NOT EXISTS yojana_registration_id TEXT;
