// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { reportingFetch } from './loudFailures';

// Comprehensive database type to handle all table structures
interface Database {
  public: {
    Tables: {
      [tableName: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
        Relationships: Array<{
          foreignKeyName: string;
          columns: string[];
          referencedRelation: string;
          referencedColumns: string[];
        }>;
      };
    };
    Views: Record<string, Record<string, unknown>>;
    Functions: {
      begin_transaction: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      commit_transaction: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      rollback_transaction: {
        Args: Record<PropertyKey, never>;
        Returns: undefined;
      };
      [key: string]: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
    };
    Enums: Record<string, string[]>;
    CompositeTypes: Record<string, Record<string, unknown>>;
  };
}

const supabaseUrl = 'https://xvkxccqaopbnkvwgyfjv.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2a3hjY3Fhb3Bibmt2d2d5Zmp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjMwMTIsImV4cCI6MjA2MzM5OTAxMn0.z9UkKHDm4RPMs_2IIzEPEYzd3-sbQSF6XpxaQg3vZhU';

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Environment variables check:', {
    supabaseUrl: supabaseUrl ? 'present' : 'missing',
    supabaseAnonKey: supabaseAnonKey ? 'present' : 'missing'
  });
  throw new Error('Missing Supabase environment variables');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// A failed write used to be silent: bills stopped saving on 28 July and it
// took until 15 August to notice. Every call goes through this fetch, so a
// refused write now says so on screen. See loudFailures.ts.
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  global: { fetch: reportingFetch },
});